[package]
name = "todotree"
version = "1.1.2"
edition = "2024"
authors = ["Manhong Dai"]
license = "MIT"
repository = "https://github.com/daimh/todotree.git"

[dependencies]
getopts = "0.2.21"
inotify = "0.11.0"
libc = "0.2.171"
